# Generated by Django 6.0.2 on 2026-03-03 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_city_alter_vagon_train_alter_train_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='is_occupied',
        ),
        migrations.RemoveField(
            model_name='train',
            name='arrival',
        ),
        migrations.RemoveField(
            model_name='train',
            name='departure',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(default='OLDTICKET', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.DateField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_arrivals', to='tickets.city')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_departures', to='tickets.city')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='tickets.train')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.trip'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('trip', 'seat')},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='train',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
    ]
