# Generated by Django 6.0.2 on 2026-03-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_remove_seat_is_occupied_remove_train_arrival_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
