# Generated by Django 6.0.2 on 2026-03-03 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_trip_arrival_alter_trip_departure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='train',
            name='source',
        ),
    ]
