# Generated by Django 6.0.2 on 2026-03-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_remove_train_destination_remove_train_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='personal_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
