# Generated by Django 6.0.2 on 2026-03-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket_first_name_ticket_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='isOccupied',
            field=models.BooleanField(default=False),
        ),
    ]
