# Generated by Django 6.0.2 on 2026-03-08 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_seat_isoccupied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='isOccupied',
        ),
    ]
